# Generated by Django 5.1.5 on 2025-04-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer_type',
            field=models.CharField(choices=[('Casual Shopper', 'Casual Shopper'), ('Discount Hunter', 'Discount Hunter'), ('One-Time Buyer', 'One-Time Buyer'), ('Loyal Customer', 'Loyal Customer'), ('Mobile-First Shopper', 'Mobile-First Shopper'), ('Social Media Buyer', 'Social Media Buyer'), ('Subscription-Based Customer', 'Subscription-Based Customer'), ('Last-Minute Buyer', 'Last-Minute Buyer')], default='Casual Shopper', max_length=50),
        ),
    ]
