version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_db
      MYSQL_USER: namdt25
      MYSQL_PASSWORD: namdt25
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce_net

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: namdt25
      POSTGRES_PASSWORD: namdt25
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - ecommerce_net 

  mongodb:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce_net
    
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: namdt25
      ME_CONFIG_BASICAUTH_PASSWORD: namdt25
    ports:
      - "8081:8081"
    networks:
      - ecommerce_net
  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    ports:
      - "8000: 8000"
    depends_on:
      - customer_service
      - cart_service
      - order_service
      - payment_service
      - shipping_service
      - product_service
    networks:
      - ecommerce_net

  customer_service:
    build: ./customer_service
    container_name: customer_service
    ports:
      - "8001:8001"
    networks:
      - ecommerce_net
    
  cart_service:
    build: ./cart_service
    container_name: cart_service
    ports:
      - "8002:8002"
    networks:
      - ecommerce_net

  order_service:
    build: ./order_service
    container_name: order_service
    ports:
      - "8003:8003"
    networks:
      - ecommerce_net

  payment_service:
    build: ./payment_service
    container_name: payment_service
    ports:
      - "8004:8004"
    networks:
      - ecommerce_net

  shipping_service:
    build: ./shipping_service
    container_name: shipping_service
    ports:
      - "8005:8005"
    networks:
      - ecommerce_net

  product_service:
    build: ./product_service
    container_name: product_service
    ports:
      - "8006:8006"
    networks:
      - ecommerce_net

volumes:
  mysql_data:
  postgres_data:
  mongo_data:

networks:
  ecommerce_net:
    driver: bridge
