# Generated by Django 5.1.7 on 2025-03-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_at_addition',
        ),
    ]
