# Generated by Django 5.1.7 on 2025-03-25 02:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_price_at_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
            preserve_default=False,
        ),
    ]
