# Generated by Django 5.1.7 on 2025-03-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.UUIDField()),
                ('tracking_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('carrier', models.CharField(max_length=100)),
                ('shipping_address', models.TextField()),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipping',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_number'], name='shipping_trackin_be38e9_idx'), models.Index(fields=['status'], name='shipping_status_85f8dc_idx'), models.Index(fields=['cart_id'], name='shipping_cart_id_796f45_idx')],
            },
        ),
    ]
